name: Build Documentation

permissions:
  contents: write

on:
  push:
    branches: [ "master" ]
    tags: 
      - 'build'
  pull_request:
    branches: [ "master" ]
    tags: 
      - 'build'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - uses: mattnotmitt/doxygen-action@v1.9.4
      with:
          doxyfile-path: 'Doxygen'
    - name: buil documentation
      run: doxygen Doxyfile

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Build documentation"

