name: Build Documentation

permissions:
  contents: write

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - uses: mattnotmitt/doxygen-action@v1.9.4
      with:
        working-directory: './'
    - name: build documentation
      run: doxygen

   # - uses: stefanzweifel/git-auto-commit-action@v4
   #   with:
   #     commit_message: "Build documentation"

