name: Build Documentation

permissions:
  contents: write

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - name: Install Doxygen
      run: sudo apt-get install doxygen -y
      shell: bash

    - name: Generate Doxygen Documentation
      run: doxygen
      shell: bash
    
    - name: Create .nojekyll
      run: touch docs/.nojekyll
      shell: bash

   # - uses: stefanzweifel/git-auto-commit-action@v4
   #   with:
   #     commit_message: "Build documentation"

